// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "msg.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace demo {

namespace {

const ::google::protobuf::Descriptor* msg_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  msg_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_msg_2eproto() {
  protobuf_AddDesc_msg_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "msg.proto");
  GOOGLE_CHECK(file != NULL);
  msg_descriptor_ = file->message_type(0);
  static const int msg_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(msg, msgtype_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(msg, msginfo_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(msg, msgfrom_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(msg, opt_),
  };
  msg_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      msg_descriptor_,
      msg::default_instance_,
      msg_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(msg, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(msg, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(msg));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_msg_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    msg_descriptor_, &msg::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_msg_2eproto() {
  delete msg::default_instance_;
  delete msg_reflection_;
}

void protobuf_AddDesc_msg_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\tmsg.proto\022\004demo\"E\n\003msg\022\017\n\007MsgType\030\001 \002("
    "\005\022\017\n\007MsgInfo\030\002 \002(\t\022\017\n\007MsgFrom\030\003 \002(\t\022\013\n\003o"
    "pt\030\004 \001(\t", 88);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "msg.proto", &protobuf_RegisterTypes);
  msg::default_instance_ = new msg();
  msg::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_msg_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_msg_2eproto {
  StaticDescriptorInitializer_msg_2eproto() {
    protobuf_AddDesc_msg_2eproto();
  }
} static_descriptor_initializer_msg_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int msg::kMsgTypeFieldNumber;
const int msg::kMsgInfoFieldNumber;
const int msg::kMsgFromFieldNumber;
const int msg::kOptFieldNumber;
#endif  // !_MSC_VER

msg::msg()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:demo.msg)
}

void msg::InitAsDefaultInstance() {
}

msg::msg(const msg& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:demo.msg)
}

void msg::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  msgtype_ = 0;
  msginfo_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  msgfrom_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  opt_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

msg::~msg() {
  // @@protoc_insertion_point(destructor:demo.msg)
  SharedDtor();
}

void msg::SharedDtor() {
  if (msginfo_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete msginfo_;
  }
  if (msgfrom_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete msgfrom_;
  }
  if (opt_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete opt_;
  }
  if (this != default_instance_) {
  }
}

void msg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* msg::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return msg_descriptor_;
}

const msg& msg::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_msg_2eproto();
  return *default_instance_;
}

msg* msg::default_instance_ = NULL;

msg* msg::New() const {
  return new msg;
}

void msg::Clear() {
  if (_has_bits_[0 / 32] & 15) {
    msgtype_ = 0;
    if (has_msginfo()) {
      if (msginfo_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        msginfo_->clear();
      }
    }
    if (has_msgfrom()) {
      if (msgfrom_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        msgfrom_->clear();
      }
    }
    if (has_opt()) {
      if (opt_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        opt_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool msg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:demo.msg)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 MsgType = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &msgtype_)));
          set_has_msgtype();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_MsgInfo;
        break;
      }

      // required string MsgInfo = 2;
      case 2: {
        if (tag == 18) {
         parse_MsgInfo:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_msginfo()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->msginfo().data(), this->msginfo().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "msginfo");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_MsgFrom;
        break;
      }

      // required string MsgFrom = 3;
      case 3: {
        if (tag == 26) {
         parse_MsgFrom:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_msgfrom()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->msgfrom().data(), this->msgfrom().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "msgfrom");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_opt;
        break;
      }

      // optional string opt = 4;
      case 4: {
        if (tag == 34) {
         parse_opt:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_opt()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->opt().data(), this->opt().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "opt");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:demo.msg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:demo.msg)
  return false;
#undef DO_
}

void msg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:demo.msg)
  // required int32 MsgType = 1;
  if (has_msgtype()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->msgtype(), output);
  }

  // required string MsgInfo = 2;
  if (has_msginfo()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->msginfo().data(), this->msginfo().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "msginfo");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->msginfo(), output);
  }

  // required string MsgFrom = 3;
  if (has_msgfrom()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->msgfrom().data(), this->msgfrom().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "msgfrom");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->msgfrom(), output);
  }

  // optional string opt = 4;
  if (has_opt()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->opt().data(), this->opt().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "opt");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->opt(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:demo.msg)
}

::google::protobuf::uint8* msg::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:demo.msg)
  // required int32 MsgType = 1;
  if (has_msgtype()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->msgtype(), target);
  }

  // required string MsgInfo = 2;
  if (has_msginfo()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->msginfo().data(), this->msginfo().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "msginfo");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->msginfo(), target);
  }

  // required string MsgFrom = 3;
  if (has_msgfrom()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->msgfrom().data(), this->msgfrom().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "msgfrom");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->msgfrom(), target);
  }

  // optional string opt = 4;
  if (has_opt()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->opt().data(), this->opt().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "opt");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->opt(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:demo.msg)
  return target;
}

int msg::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 MsgType = 1;
    if (has_msgtype()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->msgtype());
    }

    // required string MsgInfo = 2;
    if (has_msginfo()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->msginfo());
    }

    // required string MsgFrom = 3;
    if (has_msgfrom()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->msgfrom());
    }

    // optional string opt = 4;
    if (has_opt()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->opt());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void msg::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const msg* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const msg*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void msg::MergeFrom(const msg& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_msgtype()) {
      set_msgtype(from.msgtype());
    }
    if (from.has_msginfo()) {
      set_msginfo(from.msginfo());
    }
    if (from.has_msgfrom()) {
      set_msgfrom(from.msgfrom());
    }
    if (from.has_opt()) {
      set_opt(from.opt());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void msg::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void msg::CopyFrom(const msg& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool msg::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void msg::Swap(msg* other) {
  if (other != this) {
    std::swap(msgtype_, other->msgtype_);
    std::swap(msginfo_, other->msginfo_);
    std::swap(msgfrom_, other->msgfrom_);
    std::swap(opt_, other->opt_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata msg::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = msg_descriptor_;
  metadata.reflection = msg_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace demo

// @@protoc_insertion_point(global_scope)
